### PR TITLE
custom units and entities

### LINKED ISSUE #217: Include/Exclude default entities and units to load
**Is your feature request related to a problem? Please describe.**
When I want to use the default quantities and units, but parsing a big bulk of text takes a lot of time when all those default units are loaded.
Also including or excluding prefixes as some of them are not relevant in some use cases and will cause false positives, for example "atto" that catches attometres and the AM code, when AM could simply be part of a timestamp

**Describe the solution you'd like**
The ability to include/exclude default entities and units that would be loaded from the default `entities.json` and `units.json` files

### PR DESCRIPTION
**Pull request by ad-hardy**
Aims to resolve #217 

Builds on the custom classifier branch and adds functions to add custom units and entity files.

My first approach was to be the same as the custom classifier model and pass it in through the parser.parse() function, but calls to units() and entities() came from so many places and touched so much code I couldn't get it working.

Instead, we have functions in the load module to load in files./dicts which set flags to determine what gets loaded in entities() and units().

### CODE REVIEW

**Comment by adhardydm** [comment]
The Wikipedia test is failing and I've no idea why.

It runs on travis but just hangs on the first Wikipedia call on my system so I can't debug it.

**Comment by nielstron** [comment]
Did you install the Wikipedia package? Can you debug which call exactly is hanging?

**Comment by adhardydm** [comment]
`HTTPConnectionPool(host='en.wikipedia.org', port=80): Max retries exceeded with url: /w/api.php?prop=info%7Cpageprops&inprop=url&ppprop=disambiguation&redirects=&titles=Dimensionless+quantity&format=json&action=query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e799f6520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))`

Something on my network is interfering with the connection. I have a pihole adblocker + unbound DNS running and it's probably that somehow - disabling blocking doesn't help. I've not had this problem before.

The problem occours within requests, from what I can read on the wikipedia projects github page it is related to TLS certificates but I can't find a way to resolve it.

**Comment by adhardydm** [comment]
Ah, I've worked out the problem though!

All the failing units are ones from the en_US units file, so I've changed something somewhere that these are now getting loaded when the wikipedia test is running. Will try and find the bit in the code that does it.

Was it a bug that these weren't getting tested, or is it a bug that they now are?

**Comment by nielstron** [comment]
I would say it was a bug that they were not loaded before, because one requirement for units is that a Wikipedia page for them exists (for any unit language)

**Comment by adhardydm** [comment]
So I was half right: it was related to the language file. Looks like some sort of caching issue where loading of the language file was getting turned off, which meant the updates for the wikipedia URIs (pointing to the right pages) weren't getting applied.

Resetting the caches and global variables controlling unit and entity loading solved it.

**Comment by sidfeiner** [comment]
@nielstron Hey :) is there any estimation on when this will be merged?

**Comment by nielstron** [comment]
@adhardydm Let me know when this is ready for a review :)

**Comment by adhardydm** [comment]
It’s probably as good as it’s going to get - the use of global variables/caches for the units and entities has led me to implement it in a sub-optimal way but without re-engineering an awful lot of the code I don’t see a better way.

It works, I’ve been using this code successfully in my projects but it can cause some un-intuitive behaviour if not used carefully (getting cached versions with/without the custom units) which can become particularly annoying during unit testing.

Safest way I have found to use it is to import the units and entities in one place in your project (in an __init__ file for example), and import them into other modules from there, which is similar to the recommendations in Pint. Probably should write this up in the readme somewhere.

**Comment by nielstron** [comment]
If you could write this up it would be perfect, then I can try to reproduce it!

**Comment by adhardydm** [comment]
Sure! On holiday at the moment so it will probably be next week before I get round to it.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by adhardydm** [comment]
Hi @nielstron,

So the problem as I see it:

I import the example from the readme

```
from quantulum3 import load, parser

load.load_custom_units(["path/to/units.json"])
load.load_custom_entities(["path/to/entities.json"])

parser.parse("This extremely sharp tool is precise up to 0.5 slp")

[Quantity(0.5, "Unit(name="schlurp", entity=Entity("dimensionless"), uri=None)")]
```

This gives me exactly what I want, my custom unit and entity files are loaded in, the files from the package are not loaded.

Somewhere else in my project, I decide that I now want to use the units from the package

```
>>> from quantulum3 import parser
```

Now I have unexpected behaviour, the parser will have the custom units and entities from the first import. Worse, this may become inconsistent if the program runs these imports and loads in a different order for different code paths.

This is because of the use of global flags in `load` to set which units and entities are loaded and the way python loads modules. 

The variables used to control this are:

```
USE_GENERAL_UNITS
USE_GENERAL_ENTITIES
USE_LANGUAGE_UNITS
USE_LANGUAGE_ENTITIES
USE_CUSTOM_UNITS
USE_CUSTOM_ENTITIES
USE_ADDITIONAL_UNITS
USE_ADDITIONAL_ENTITIES
```

This is necassary because of the use `@cached` decorator to keep a version of the Units and Entities classes loaded (as this is a slow process, so we want caching!). We could have extended the cached decorator so that it stores the general/language/custom/additional units as args, but because sometimes these are dictionaries (and we can't hash a dictionary) this doesn't work.

There are tools I have created to help manage this:

```
from quantulum3 import load, parser

load.clear_caches()
load.reset_units_and_entities_loading

# now we will be back as if we had not loaded any custom units/entities and will have the packaged version
```

This all isn't good and is exactly the sort of reason to avoid using these sorts of global flags.

I think the best way to handle all of this would be for the user to create the custom entities and classes in their project, and pass them into the parser function as an arg (with default classes created as they are at the moment by default). I tried something similar when I initially did this but the entities and units are called from so many places and I don't know the code well enough that I got very lost.

**Comment by nielstron** [comment]
Thanks for this detailed rundown. Can we just fix that the recommended way to set custom entities is

```python


# load stuff...
from quantulum import load
load.add_custom_quantities(...)

# do work
from quantulum import parser
parser.parse(...)

# unload stuff
load.reset_quantities(...)
```

If I see it right than within "do work" the quantities should be right (unless someone calls add custom quantities in there which I don't think will happen and anyways is under control of the user)


I agree its not pretty but would consider it a reasonable workaround for now.

**Comment by adhardydm** [comment]
Thans for the suggestions. I'll grab a look when I can and rename some stuff and add some documentation.

I'll maybe add a context manager that loads and unloads the custom units so that there's a really simple way for people to use this. Something like:

``` python
with load.custom_units("path/to/units", "path/to/entities"):
   # parse with custom units
   parser(..)

# parse with default units
parser(...)
```

**Comment by nielstron** [comment]
That's a great idea!

**Comment by adhardydm** [comment]
> I think I'm done with that now.
> 
> I'm getting really strange test results locally on the parser tests (both classifier and non-classifier) but I'll save that for another issue if I can't solve it as it looks like it's working fine on Travis.

Ran the build script, seems to be happy now.

**Comment by adhardydm** [comment]
Ready for review!

**Comment by ad-hardy** [comment]
Hi @nielstron, are you planning on merging this PR? I have several projects that depend on it and will need to release a fork otherwise.

**Pull request merged**
