### PR TITLE
edited the number pattern regex to allow for a unicode fraction inste…

### PR DESCRIPTION
**Pull request by bajisci**
#159 
this regex edit allows for a unicode fraction to be the leading number for a unit of measurement.

### CODE REVIEW

**Comment by nielstron** [comment]
Great thanks for the PR! :) I'll have to.investigate a bit whether this breaks any valid input but it lools good to.me

**Comment by bajisci** [comment]
Looks like the build failed so maybe it was a bit premature after this was working for my use case, my apologies!

**Comment by bajisci** [comment]
I'll see if I can fix it tomorrow

**Comment by nielstron** [comment]
Thanks for the change! Please also add some test cases for your change (i.e. sentences that contain unicode-only fractions) to see if it actually works

**Comment by bajisci** [comment]
Ah my fork wasnt updated

**Pull request merged**
